export const mainProducts = [
  {
    id: 1,
    img: "food-1.png",
    name: "delicious food",
    price: 40,
    category: "drinks",
  },
  {
    id: 2,
    img: "food-2.png",
    name: "delicious food",
    price: 55,
    category: "drinks",
  },
  {
    id: 3,
    img: "food-3.png",
    name: "delicious food",
    price: 30,
    category: "drinks",
  },
  {
    id: 4,
    img: "food-4.png",
    name: "delicious food",
    price: 60,
    category: "drinks",
  },
  {
    id: 5,
    img: "food-5.png",
    name: "delicious food",
    price: 55,
    category: "drinks",
  },
  {
    id: 6,
    img: "food-6.png",
    name: "delicious food",
    price: 20,
    category: "drinks",
  },
  {
    id: 7,
    img: "food-7.png",
    name: "delicious food",
    price: 15,
    category: "drinks",
  },
  {
    id: 8,
    img: "food-8.png",
    name: "delicious food",
    price: 30,
    category: "drinks",
  },
];

export const cartProducts = [
  {
    id: 1,
    img: "menu-1.png",
    name: "delicious food",
    price: 40,
    category: "drinks",
    quantity: 2,
  },
  {
    id: 2,
    img: "menu-2.png",
    name: "delicious food",
    price: 55,
    category: "drinks",
    quantity: 3,
  },
  {
    id: 3,
    img: "menu-3.png",
    name: "delicious food",
    price: 30,
    category: "drinks",
    quantity: 1,
  },
  {
    id: 4,
    img: "menu-4.png",
    name: "delicious food",
    price: 60,
    category: "drinks",
    quantity: 3,
  },
  {
    id: 5,
    img: "menu-5.png",
    name: "delicious food",
    price: 55,
    category: "drinks",
    quantity: 1,
  },
];
