export const mainProducts = [
  {
    _id: 10,
    img: "pizza-8.png",
    name: "Margherita Pizza",
    price: 5.99,
    category: "pizzas",
    desc: "Lorem ipsum dolor sit amet, ne commodo amet, aeneanc dolor sit amet reku aeneanc Lorem dolor sit elit.",
  },
  // {
  //   _id: 9,
  //   img: "menu-1.png",
  //   name: "Carolina burger",
  //   price: 25.99,
  //   category: "burgers",
  //   desc: "Lorem ipsum dolor sit amet, ne commodo amet, aeneanc dolor sit amet reku aeneanc Lorem dolor sit elit.",
  // },
  // {
  //   _id: 14,
  //   img: "dish-1.png",
  //   name: "Chori burger",
  //   price: 8.99,
  //   category: "burgers",
  //   desc: "Lorem ipsum dolor sit amet, ne commodo amet, aeneanc dolor sit amet reku aeneanc Lorem dolor sit elit.",
  // },
  {
    _id: 20,
    img: "pizza-1.png",
    name: "Chicken Pizza",
    price: 2.99,
    category: "pizzas",
    desc: "Lorem ipsum dolor sit amet, ne commodo amet, aeneanc dolor sit amet reku aeneanc Lorem dolor sit elit.",
  },
  {
    _id: 21,
    img: "pizza-2.png",
    name: "Sicilian pizza",
    price: 3.99,
    category: "pizzas",
    desc: "Lorem ipsum dolor sit amet, ne commodo amet, aeneanc dolor sit amet reku aeneanc Lorem dolor sit elit.",
  },
  // {
  //   _id: 22,
  //   img: "pizza-3.png",
  //   name: "Italian pizza",
  //   price: 40.99,
  //   category: "pizzas",
  //   desc: "Lorem ipsum dolor sit amet, ne commodo amet, aeneanc dolor sit amet reku aeneanc Lorem dolor sit elit.",
  // },
  // {
  //   _id: 23,
  //   img: "pizza-4.png",
  //   name: "Detroit Pizza",
  //   price: 35.99,
  //   category: "pizzas",
  //   desc: "Lorem ipsum dolor sit amet, ne commodo amet, aeneanc dolor sit amet reku aeneanc Lorem dolor sit elit.",
  // },
  // {
  //   _id: 24,
  //   img: "pizza-5.png",
  //   name: "Meat Pizza",
  //   price: 60.99,
  //   category: "pizzas",
  //   desc: "Lorem ipsum dolor sit amet, ne commodo amet, aeneanc dolor sit amet reku aeneanc Lorem dolor sit elit.",
  // },
  {
    _id: 25,
    img: "pizza-6.png",
    name: "Greek Pizza",
    price: 6.99,
    category: "pizzas",
    desc: "Lorem ipsum dolor sit amet, ne commodo amet, aeneanc dolor sit amet reku aeneanc Lorem dolor sit elit.",
  },
  // {
  //   _id: 26,
  //   img: "pizza-7.png",
  //   name: "Chicago Pizza",
  //   price: 8.99,
  //   category: "pizzas",
  //   desc: "Lorem ipsum dolor sit amet, ne commodo amet, aeneanc dolor sit amet reku aeneanc Lorem dolor sit elit.",
  // },
  // {
  //   _id: 27,
  //   img: "burger-1.png",
  //   name: "Hawaii burger",
  //   price: 60.99,
  //   category: "burgers",
  //   desc: "Lorem ipsum dolor sit amet, ne commodo amet, aeneanc dolor sit amet reku aeneanc Lorem dolor sit elit.",
  // },
  {
    _id: 28,
    img: "burger-2.png",
    name: "Cheese Burger",
    price: 8.99,
    category: "burgers",
    desc: "Lorem ipsum dolor sit amet, ne commodo amet, aeneanc dolor sit amet reku aeneanc Lorem dolor sit elit.",
  },
  {
    _id: 30,
    img: "burger-4.png",
    name: "Chilli burger",
    price: 15.99,
    category: "burgers",
    desc: "Lorem ipsum dolor sit amet, ne commodo amet, aeneanc dolor sit amet reku aeneanc Lorem dolor sit elit.",
  },

  {
    _id: 32,
    img: "burger-6.png",
    name: "Banquet burger	",
    price: 5.99,
    category: "burgers",
    desc: "Lorem ipsum dolor sit amet, ne commodo amet, aeneanc dolor sit amet reku aeneanc Lorem dolor sit elit.",
  },
  // {
  //   _id: 33,
  //   img: "burger-7.png",
  //   name: "Bacon Burger",
  //   price: 50.99,
  //   category: "burgers",
  //   desc: "Lorem ipsum dolor sit amet, ne commodo amet, aeneanc dolor sit amet reku aeneanc Lorem dolor sit elit.",
  // },
  // {
  //   _id: 34,
  //   img: "burger-8.png",
  //   name: "Angus burger	",
  //   price: 35.99,
  //   category: "burgers",
  //   desc: "Lorem ipsum dolor sit amet, ne commodo amet, aeneanc dolor sit amet reku aeneanc Lorem dolor sit elit.",
  // },
  {
    _id: 35,
    img: "chicken-1.png",
    name: "Fried Chicken",
    price: 13.99,
    category: "chickens",
    desc: "Lorem ipsum dolor sit amet, ne commodo amet, aeneanc dolor sit amet reku aeneanc Lorem dolor sit elit.",
  },
  {
    _id: 36,
    img: "chicken-2.png",
    name: "Roast Chicken",
    price: 8.99,
    category: "chickens",
    desc: "Lorem ipsum dolor sit amet, ne commodo amet, aeneanc dolor sit amet reku aeneanc Lorem dolor sit elit.",
  },
  {
    _id: 37,
    img: "chicken-3.png",
    name: "White Chicken",
    price: 9.99,
    category: "chickens",
    desc: "Lorem ipsum dolor sit amet, ne commodo amet, aeneanc dolor sit amet reku aeneanc Lorem dolor sit elit.",
  },
  {
    _id: 42,
    img: "chicken-8.png",
    name: "Tikka Chicken",
    price: 18.99,
    category: "chickens",
    desc: "Lorem ipsum dolor sit amet, ne commodo amet, aeneanc dolor sit amet reku aeneanc Lorem dolor sit elit.",
  },
  {
    _id: 43,
    img: "lunch-1.png",
    name: "Tikka Lunch",
    price: 16.99,
    category: "lunch",
    desc: "Lorem ipsum dolor sit amet, ne commodo amet, aeneanc dolor sit amet reku aeneanc Lorem dolor sit elit.",
  },
  {
    _id: 44,
    img: "lunch-2.png",
    name: "Cilantro Lime",
    price: 14.99,
    category: "lunch",
    desc: "Lorem ipsum dolor sit amet, ne commodo amet, aeneanc dolor sit amet reku aeneanc Lorem dolor sit elit.",
  },
  {
    _id: 45,
    img: "lunch-3.png",
    name: "Ponno Tenders",
    price: 9.99,
    category: "lunch",
    desc: "Lorem ipsum dolor sit amet, ne commodo amet, aeneanc dolor sit amet reku aeneanc Lorem dolor sit elit.",
  },
  {
    _id: 46,
    img: "lunch-4.png",
    name: "Rice Pilaf",
    price: 18.99,
    category: "lunch",
    desc: "Lorem ipsum dolor sit amet, ne commodo amet, aeneanc dolor sit amet reku aeneanc Lorem dolor sit elit.",
  },
  {
    _id: 47,
    img: "drink-1.png",
    name: "espresso coffee",
    price: 1.99,
    category: "drinks",
    desc: "Lorem ipsum dolor sit amet, ne commodo amet, aeneanc dolor sit amet reku aeneanc Lorem dolor sit elit.",
  },
  {
    _id: 48,
    img: "drink-2.png",
    name: "orange juice",
    price: 2.99,
    category: "drinks",
    desc: "Lorem ipsum dolor sit amet, ne commodo amet, aeneanc dolor sit amet reku aeneanc Lorem dolor sit elit.",
  },
  {
    _id: 49,
    img: "drink-3.png",
    name: "Coca drink",
    price: 1.99,
    category: "drinks",
    desc: "Lorem ipsum dolor sit amet, ne commodo amet, aeneanc dolor sit amet reku aeneanc Lorem dolor sit elit.",
  },
  {
    _id: 50,
    img: "drink-4.png",
    name: "Latte coffee",
    price: 1.99,
    category: "drinks",
    desc: "Lorem ipsum dolor sit amet, ne commodo amet, aeneanc dolor sit amet reku aeneanc Lorem dolor sit elit.",
  },
  {
    _id: 55,
    img: "popular-5.png",
    name: "Chori combo",
    price: 2.99,
    category: "popular",
    desc: "Lorem ipsum dolor sit amet, ne commodo amet, aeneanc dolor sit amet reku aeneanc Lorem dolor sit elit.",
  },
  {
    _id: 51,
    img: "popular-1.png",
    name: "Chilli combo",
    price: 5.99,
    category: "popular",
    desc: "Lorem ipsum dolor sit amet, ne commodo amet, aeneanc dolor sit amet reku aeneanc Lorem dolor sit elit.",
  },
  {
    _id: 60,
    img: "popular-02.png",
    name: "Bacon combo",
    price: 10.99,
    category: "popular",
    desc: "Lorem ipsum dolor sit amet, ne commodo amet, aeneanc dolor sit amet reku aeneanc Lorem dolor sit elit.",
  },
  {
    _id: 61,
    img: "popular-02.png",
    name: "Beef Meat",
    price: 9.99,
    category: "meats",
    desc: "Lorem ipsum dolor sit amet, ne commodo amet, aeneanc dolor sit amet reku aeneanc Lorem dolor sit elit.",
  },
  {
    _id: 62,
    img: "popular-02.png",
    name: "Taurus Meat",
    price: 12.99,
    category: "meats",
    desc: "Lorem ipsum dolor sit amet, ne commodo amet, aeneanc dolor sit amet reku aeneanc Lorem dolor sit elit.",
  },
  {
    _id: 63,
    img: "popular-02.png",
    name: "Cattle Meat",
    price: 9.99,
    category: "meats",
    desc: "Lorem ipsum dolor sit amet, ne commodo amet, aeneanc dolor sit amet reku aeneanc Lorem dolor sit elit.",
  },
  {
    _id: 64,
    img: "popular-02.png",
    name: "Deer Meat",
    price: 9.99,
    category: "meats",
    desc: "Lorem ipsum dolor sit amet, ne commodo amet, aeneanc dolor sit amet reku aeneanc Lorem dolor sit elit.",
  },
];
