export const mainProducts = [
  {
    id: 9,
    img: "menu-1.png",
    name: "Carolina burger",
    price: 25,
    category: "burgers",
  },
  {
    id: 10,
    img: "pizza-8.png",
    name: "Margherita Pizza",
    price: 50,
    category: "pizzas",
  },
  {
    id: 14,
    img: "dish-1.png",
    name: "Chori burger",
    price: 30,
    category: "burgers",
  },
  {
    id: 20,
    img: "pizza-1.png",
    name: "Chicken Pizza",
    price: 55,
    category: "pizzas",
  },
  {
    id: 21,
    img: "pizza-2.png",
    name: "Sicilian pizza",
    price: 45,
    category: "pizzas",
  },
  {
    id: 22,
    img: "pizza-3.png",
    name: "Italian pizza",
    price: 40,
    category: "pizzas",
  },
  {
    id: 23,
    img: "pizza-4.png",
    name: "Detroit Pizza",
    price: 35,
    category: "pizzas",
  },
  {
    id: 24,
    img: "pizza-5.png",
    name: "Meat Pizza",
    price: 60,
    category: "pizzas",
  },
  {
    id: 25,
    img: "pizza-6.png",
    name: "Greek Pizza",
    price: 25,
    category: "pizzas",
  },
  {
    id: 26,
    img: "pizza-7.png",
    name: "Chicago Pizza",
    price: 30,
    category: "pizzas",
  },
  {
    id: 27,
    img: "burger-1.png",
    name: "Hawaii burger",
    price: 60,
    category: "burgers",
  },
  {
    id: 28,
    img: "burger-2.png",
    name: "Cheese Burger",
    price: 30,
    category: "burgers",
  },
  {
    id: 30,
    img: "burger-4.png",
    name: "Chilli burger",
    price: 55,
    category: "burgers",
  },

  {
    id: 32,
    img: "burger-6.png",
    name: "Banquet burger	",
    price: 60,
    category: "burgers",
  },
  {
    id: 33,
    img: "burger-7.png",
    name: "Bacon Burger",
    price: 50,
    category: "burgers",
  },
  {
    id: 34,
    img: "burger-8.png",
    name: "Angus burger	",
    price: 35,
    category: "burgers",
  },
  {
    id: 35,
    img: "chicken-1.png",
    name: "Fried Chicken",
    price: 40,
    category: "chickens",
  },
  {
    id: 36,
    img: "chicken-2.png",
    name: "Roast Chicken",
    price: 30,
    category: "chickens",
  },
  {
    id: 37,
    img: "chicken-3.png",
    name: "White Chicken",
    price: 80,
    category: "chickens",
  },
  {
    id: 42,
    img: "chicken-8.png",
    name: "Tikka Chicken",
    price: 65,
    category: "chickens",
  },
  {
    id: 43,
    img: "lunch-1.png",
    name: "Tikka Chicken",
    price: 90,
    category: "lunch",
  },
  {
    id: 44,
    img: "lunch-2.png",
    name: "Cilantro Lime",
    price: 95,
    category: "lunch",
  },
  {
    id: 45,
    img: "lunch-3.png",
    name: "Chicken Tenders",
    price: 80,
    category: "lunch",
  },
  {
    id: 46,
    img: "lunch-4.png",
    name: "Rice Pilaf",
    price: 90,
    category: "lunch",
  },
  {
    id: 47,
    img: "drink-1.png",
    name: "espresso coffee",
    price: 10,
    category: "drinks",
  },
  {
    id: 48,
    img: "drink-2.png",
    name: "orange juice",
    price: 15,
    category: "drinks",
  },
  {
    id: 49,
    img: "drink-3.png",
    name: "Coca drink",
    price: 12,
    category: "drinks",
  },
  {
    id: 50,
    img: "drink-4.png",
    name: "Latte coffee",
    price: 18,
    category: "drinks",
  },
  {
    id: 55,
    img: "popular-5.png",
    name: "Chori burger combo",
    price: 18,
    category: "popular",
  },
  {
    id: 51,
    img: "popular-1.png",
    name: "Chilli burger combo",
    price: 18,
    category: "popular",
  },
  {
    id: 54,
    img: "popular-02.png",
    name: "Bacon burger combo",
    price: 18,
    category: "popular",
  },
];
